apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-server
  labels:
    app: node-express-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-express-server
  template:
    metadata:
      labels:
        app: node-express-server
    spec:
      containers:
      - name: node-express-server
        image: sampritchard13/node-express-jenkins-2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-server-service
spec:
  type: NodePort
  selector:
    app: node-express-server
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
